# Generated by Django 4.1.7 on 2023-05-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaProyectoApp', '0002_challenge_creator_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
