# Generated by Django 4.1.7 on 2023-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaProyectoApp', '0006_userchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='total_tests',
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
