# Generated by Django 4.1.7 on 2023-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaProyectoApp', '0007_remove_challenge_total_tests_challenge_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='instructions',
            field=models.TextField(default=None),
        ),
    ]
