# Generated by Django 4.1.7 on 2023-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaProyectoApp', '0008_challenge_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='instructions',
            field=models.TextField(),
        ),
    ]
