# Generated by Django 4.1.7 on 2023-05-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaProyectoApp', '0010_response_userscore_delete_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='solution',
            field=models.TextField(default=None),
        ),
    ]
