# Generated by Django 4.1.7 on 2023-05-15 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PruebaProyectoApp', '0013_solution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('user', 'challenge', 'solution')},
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
